apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: schema_change
    component: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schema_change
      component: app
  template:
    metadata:
      labels:
        app: schema_change
        component: app
    spec:
      containers:
        - name: app
          image: schema_app:0.0.0
          command:
            - python
            - app.py
            - generate
