apiVersion: batch/v1
kind: Job
metadata:
  name: db-add-type
  labels:
    app: schema_change
    component: db_add_type_job
spec:
  template:
    spec:
      containers:
      - name: db-add-type
        image: schema_alembic:0.0.0
        command:
          - alembic
          - upgrade
          - d7a332a59baf
      restartPolicy: Never
