apiVersion: batch/v1
kind: Job
metadata:
  name: dbsetup
  labels:
    app: schema_change
    component: db_setup_job
spec:
  template:
    spec:
      containers:
      - name: dbsetup
        image: schema_app:0.0.1
        command:
          - python
          - app.py
          - setup
          - "--version=1"
      restartPolicy: Never
