apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: schema_change
    component: monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schema_change
      component: monitor
  template:
    metadata:
      labels:
        app: schema_change
        component: monitor
    spec:
      containers:
        - name: monitor
          image: schema_app:0.0.2
          command:
            - python
            - app.py
            - monitor
            - "--version"
            - "1"
