version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  fsa:
    level: DEBUG
  app:
    level: DEBUG
  sqlalchemy.engine:
    level: WARN
    propagate: False
  alembic:
    level: INFO
    propagate: False
root:
  level: DEBUG
  handlers: [console]
